repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      # lint
      - id: ruff
        types_or: [ python ]
        language: python
      # format
      - id: ruff-format
        types_or: [ python ]