name: Go

on:
  push:
    branches: [ "**" ]
    paths: [ "server/**" ]
  pull_request:
    branches: [ "**" ]
    paths: [ "server/**" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: ./server/go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
